### ISSUE TITLE
Framework or Package + Demo

### ISSUE THREAD

**Issue by ghost** [w3c/wot-go#3]
A common practice of Go projects is not to define frameworks, but packages (or libraries). Are we using the wrong terminology here? Maybe we just need a well defined package, and a well defined demo server using this package.

**Comment by ghost** [comment]
I'm also confused a bit about the terminology and what is expected of this project. Is this going to be a full-fledged WoT server, or is it supposed to be a package and demo implementation?

**Comment by draggett** [comment]
> On 27 Jun 2015, at 18:07, Herbert Fischer notifications@github.com wrote:
> 
> A common practice of Go projects is not to define frameworks, but packages (or libraries). Are we using the wrong terminology here? Maybe we just need a well defined package, and a well defined demo server using this package.

Right, the Go implementation of the Web of Things framework is a Go package (or packages).   We need a clean separation between the protocol independent functionality and the code to support individual protocols and data encodings.

—
   Dave Raggett <dsr@w3.org <mailto:dsr@w3.org>>

**Comment by draggett** [comment]
> On 27 Jun 2015, at 18:43, Herbert Fischer notifications@github.com wrote:
> 
> I'm also confused a bit about the terminology and what is expected of this project. Is this going to be a full-fledged WoT server, or is it supposed to be a package and demo implementation?

My aim is an evolutionary progression from a simple demo into a fully fledged server.  A long journey begins will a single step ...

—
   Dave Raggett <dsr@w3.org <mailto:dsr@w3.org>>

**Comment by ghost** [comment]
Thanks @draggett
